// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyScuUhA7EkJHgPAHjPKFzFnPaF_OcckQ',
    appId: '1:465584378697:web:1de3ea5093ddaf49f94098',
    messagingSenderId: '465584378697',
    projectId: 'pocket-patners',
    authDomain: 'pocket-patners.firebaseapp.com',
    storageBucket: 'pocket-patners.appspot.com',
    measurementId: 'G-0BBJW9J1KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Xv3ZtzvoVwYRyJBeiULBLeQBgXpZhsU',
    appId: '1:465584378697:android:c883d287ee2aff23f94098',
    messagingSenderId: '465584378697',
    projectId: 'pocket-patners',
    storageBucket: 'pocket-patners.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs81kG-IlZyJPj5BjxGXDPvKDNkh3GM0o',
    appId: '1:465584378697:ios:42dbc50351e8fb3cf94098',
    messagingSenderId: '465584378697',
    projectId: 'pocket-patners',
    storageBucket: 'pocket-patners.appspot.com',
    iosBundleId: 'com.example.agrocuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs81kG-IlZyJPj5BjxGXDPvKDNkh3GM0o',
    appId: '1:465584378697:ios:42dbc50351e8fb3cf94098',
    messagingSenderId: '465584378697',
    projectId: 'pocket-patners',
    storageBucket: 'pocket-patners.appspot.com',
    iosBundleId: 'com.example.agrocuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyScuUhA7EkJHgPAHjPKFzFnPaF_OcckQ',
    appId: '1:465584378697:web:bf58915ef74c6490f94098',
    messagingSenderId: '465584378697',
    projectId: 'pocket-patners',
    authDomain: 'pocket-patners.firebaseapp.com',
    storageBucket: 'pocket-patners.appspot.com',
    measurementId: 'G-VCGGLJVQTM',
  );
}
